# Generated by Django 5.2.4 on 2025-07-17 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotor', '0003_promotor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotor',
            name='senha',
        ),
    ]
