# Generated by Django 5.2.4 on 2025-07-17 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotor', '0004_remove_promotor_senha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coordenador',
        ),
    ]
